Update readthedocs config
This config line was causing an error over in readthedocs:

```
Running Sphinx v8.1.3
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
['/home/docs/checkouts/readthedocs.org/user_builds/pymarc/checkouts/latest/docs/source', '/home/docs/.asdf/installs/python/3.11.9/lib/python311.zip', '/home/docs/.asdf/installs/python/3.11.9/lib/python3.11', '/home/docs/.asdf/installs/python/3.11.9/lib/python3.11/lib-dynload', '/home/docs/checkouts/readthedocs.org/user_builds/pymarc/envs/latest/lib/python3.11/site-packages', '/home/docs/checkouts/readthedocs.org/user_builds/pymarc/checkouts/latest/docs/source/../..']
loading translations [en]... done
making output directory... done
WARNING: html_static_path entry '_static' does not exist
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
ERROR: Invalid value `None` in intersphinx_mapping['https://docs.python.org/']. Expected a two-element tuple or list.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymarc/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 496, in build_main
    app = Sphinx(
          ^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymarc/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 280, in __init__
    self.events.emit('config-inited', self.config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymarc/envs/latest/lib/python3.11/site-packages/sphinx/events.py", line 404, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymarc/envs/latest/lib/python3.11/site-packages/sphinx/ext/intersphinx/_load.py", line 132, in validate_intersphinx_mapping
    raise ConfigError(msg)
sphinx.errors.ConfigError: Invalid `intersphinx_mapping` configuration (1 error).

Configuration error:
Invalid `intersphinx_mapping` configuration (1 error).
```